import type { DeviceProfile } from '../types';

/**
 * Model profiles.
 *
 * SKU ↔ model mapping verified against Anker's own "find your serial number"
 * service pages and cross-checked with an independent open-source Soundcore
 * client's device table. Getting these right matters: `matchDevice` picks the
 * profile from the name Windows advertises, and the profile decides which ANC
 * frame layout is sent and how raw battery steps are scaled.
 *
 * Two long-standing errors are fixed here:
 *   - A3948 is the A20i / A25i. P20i / P25i / R50i are A3949.
 *   - A3949 is the *non*-ANC R50i family. R50i NC shares A3959 with the P30i.
 * The old table had those swapped, so a plain R50i was shown ANC controls and
 * an A20i was treated as a P20i.
 *
 * ORDER MATTERS. `matchDevice` uses substring aliases and returns the first
 * hit, so the ANC-capable R50i NC profile must stay ahead of the plain R50i
 * profile: "soundcore R50i NC" contains "R50i".
 */

/** Hand-verified against captures and the protocol notes in PROTOCOL.md. */
export const VERIFIED_DEVICES: DeviceProfile[] = [
  {
    id: 'r50i-nc',
    name: 'R50i NC',
    sku: 'A3959',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    names: ['R50i NC', 'A3959', 'soundcore R50i NC'],
  },
  {
    id: 'p30i',
    name: 'P30i',
    sku: 'A3959',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 10,
    // A3959 covers both the P30i and the R50i NC; the advertised name is what
    // separates them, so keep this alias list to P30i spellings only.
    names: ['P30i', 'soundcore P30i'],
  },
  {
    id: 'p20i',
    name: 'P20i / P25i / R50i',
    sku: 'A3949',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    // R50i here is the base model. The NC variant is A3959 and matches the
    // profile above first, so listing 'R50i' does not steal it.
    names: ['P20i', 'P25i', 'R50i', 'A3949', 'soundcore P20i', 'soundcore P25i', 'soundcore R50i'],
  },
  {
    id: 'a20i',
    name: 'A20i / A25i',
    sku: 'A3948',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['A20i', 'A25i', 'A3948', 'soundcore A20i', 'soundcore A25i'],
  },
  {
    id: 'liberty-4-nc',
    name: 'Liberty 4 NC',
    sku: 'A3947',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Liberty 4 NC', 'A3947', 'soundcore Liberty 4 NC'],
  },
  {
    id: 'liberty-4',
    name: 'Liberty 4',
    sku: 'A3953',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Liberty 4', 'A3953', 'soundcore Liberty 4'],
  },
  {
    id: 'liberty-3-pro',
    name: 'Liberty 3 Pro',
    sku: 'A3952',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: false,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Liberty 3 Pro', 'A3952', 'soundcore Liberty 3 Pro'],
  },
  {
    id: 'space-one',
    name: 'Space One',
    sku: 'A3035',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: true,
    scenes: true,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Space One', 'A3035', 'soundcore Space One'],
  },
  {
    id: 'q45',
    name: 'Space Q45',
    sku: 'A3040',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Q45', 'Space Q45', 'A3040', 'soundcore Space Q45'],
  },
  {
    id: 'q35',
    name: 'Life Q35',
    sku: 'A3029',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: true,
    dual: false,
    batteryMax: 5,
    names: ['Q35', 'Life Q35', 'A3029', 'soundcore Life Q35'],
  },
  {
    id: 'q30',
    name: 'Life Q30',
    sku: 'A3028',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Q30', 'Life Q30', 'A3028', 'Soundcore Life Q30'],
  },
  {
    id: 'life-tune',
    name: 'Life Tune',
    sku: 'A3027',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Life Tune', 'A3027', 'soundcore Life Tune'],
  },
  {
    id: 'sport-x10',
    name: 'Sport X10',
    sku: 'A3961',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Sport X10', 'A3961', 'soundcore Sport X10'],
  },
  {
    id: 'sleep-a10',
    name: 'Sleep A10',
    sku: 'A6610',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Sleep A10', 'A6610', 'soundcore Sleep A10'],
  },
];

/**
 * Models that appear in the official soundcore app 6.4.0 model list (taken from
 * the per-SKU UI resources shipped inside the APK) and whose SKU is confirmed
 * by Anker's own serial-number documentation.
 *
 * `inferred: true` means the *capability flags* were derived from the product
 * family and published specs, not read back from the hardware — the official
 * app keeps per-device feature data server-side, so it cannot be verified from
 * the APK. Treat these as sensible defaults, and correct them from a live
 * device or a capture before trusting a flag. The ANC frame family only depends
 * on `family` (TWS vs over-ear), which is a hardware property and is reliable.
 */
export const DISCOVERED_DEVICES: DeviceProfile[] = [
  {
    id: 'liberty-5',
    name: 'Liberty 5',
    sku: 'A3957',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Liberty 5', 'A3957', 'soundcore Liberty 5'],
  },
  {
    id: 'liberty-4-pro',
    name: 'Liberty 4 Pro',
    sku: 'A3954',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Liberty 4 Pro', 'A3954', 'soundcore Liberty 4 Pro'],
  },
  {
    id: 'liberty-air-2-pro',
    name: 'Liberty Air 2 Pro',
    sku: 'A3951',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Liberty Air 2 Pro', 'A3951'],
  },
  {
    id: 'p40i',
    name: 'P40i',
    sku: 'A3955',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['P40i', 'A3955', 'soundcore P40i'],
  },
  {
    id: 'a30i',
    name: 'A30i',
    sku: 'A3958',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['A30i', 'A3958', 'soundcore A30i'],
  },
  {
    id: 'space-a40',
    name: 'Space A40',
    sku: 'A3936',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Space A40', 'A3936', 'soundcore Space A40'],
  },
  {
    id: 'space-one-pro',
    name: 'Space One Pro',
    sku: 'A3062',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: true,
    scenes: true,
    ldac: true,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Space One Pro', 'A3062', 'soundcore Space One Pro'],
  },
  {
    id: 'q20i',
    name: 'Q20i',
    sku: 'A3004',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Q20i', 'A3004', 'soundcore Q20i'],
  },
  {
    id: 'q11i',
    name: 'Q11i',
    sku: 'A3005',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Q11i', 'A3005', 'soundcore Q11i'],
  },
  {
    id: 'life-tune-pro',
    name: 'Life Tune Pro',
    sku: 'A3030',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life Tune Pro', 'A3030'],
  },
  {
    id: 'p41i',
    name: 'P41i',
    sku: 'A3937',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['P41i', 'A3937', 'soundcore P41i'],
  },
  {
    id: 'sport-x20',
    name: 'Sport X20',
    sku: 'A3968',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['Sport X20', 'A3968', 'soundcore Sport X20'],
  },
  {
    id: 'sleep-a20',
    name: 'Sleep A20',
    sku: 'A6611',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Sleep A20', 'A6611', 'soundcore Sleep A20'],
  },
  {
    id: 'sleep-a30',
    name: 'Sleep A30',
    sku: 'D1301',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Sleep A30', 'D1301', 'soundcore Sleep A30'],
  },
  {
    id: 'life-dot-2-nc',
    name: 'Life Dot 2 NC',
    sku: 'A3931',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life Dot 2 NC', 'A3931'],
  },
  {
    id: 'life-p3',
    name: 'Life P3',
    sku: 'A3939',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life P3', 'A3939'],
  },
  {
    id: 'life-a2-nc',
    name: 'Life A2 NC',
    sku: 'A3935',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life A2 NC', 'A3935'],
  },
  {
    id: 'life-note-3',
    name: 'Life Note 3',
    sku: 'A3933',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life Note 3', 'A3933'],
  },
  {
    id: 'life-p2-mini',
    name: 'Life P2 Mini',
    sku: 'A3944',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life P2 Mini', 'A3944'],
  },
  {
    id: 'life-note-3s',
    name: 'Life Note 3S',
    sku: 'A3945',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['Life Note 3S', 'A3945'],
  },
  {
    id: 'c30i',
    name: 'C30i',
    sku: 'A3330',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['C30i', 'A3330', 'soundcore C30i'],
  },
  {
    id: 'c40i',
    name: 'C40i',
    sku: 'A3331',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['C40i', 'A3331', 'soundcore C40i'],
  },
  {
    id: 'aerofit-2',
    name: 'AeroFit 2',
    sku: 'A3874',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['AeroFit 2', 'A3874'],
  },
  {
    id: 'v20i',
    name: 'V20i',
    sku: 'A3876',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['V20i', 'A3876', 'soundcore V20i'],
  },
  {
    id: 'k20i',
    name: 'K20i',
    sku: 'A3994',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['K20i', 'A3994', 'soundcore K20i'],
  },
  {
    id: 'r60i-nc',
    name: 'R60i NC',
    sku: 'D1202C',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    inferred: true,
    names: ['R60i NC', 'D1202C', 'soundcore R60i NC'],
  },
  {
    id: 'p31i',
    name: 'P31i',
    sku: 'D1202',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['P31i', 'D1202', 'soundcore P31i'],
  },
  {
    id: 'c50i',
    name: 'C50i',
    sku: 'D1101',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    inferred: true,
    names: ['C50i', 'D1101', 'soundcore C50i'],
  },
];

export const DEVICES: DeviceProfile[] = [...VERIFIED_DEVICES, ...DISCOVERED_DEVICES];

/** Fallback when nothing matches; the first entry is the best-documented unit. */
export const DEFAULT_DEVICE = VERIFIED_DEVICES[0];

export function matchDevice(name: string | undefined | null): DeviceProfile {
  if (!name) return DEFAULT_DEVICE;
  const n = name.toLowerCase();
  const hit = DEVICES.find((d) =>
    d.names.some((alias) => n.includes(alias.toLowerCase())) || n.includes(d.sku.toLowerCase()),
  );
  return hit ?? DEFAULT_DEVICE;
}

export function findDeviceById(id: string): DeviceProfile | undefined {
  return DEVICES.find((d) => d.id === id);
}
