import type { DeviceProfile } from '../types';

export const DEVICES: DeviceProfile[] = [
  {
    id: 'r50i-nc',
    name: 'R50i NC',
    sku: 'A3949',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 5,
    names: ['R50i', 'A3949', 'soundcore R50i', 'soundcore R50i NC'],
  },
  {
    id: 'p30i',
    name: 'P30i',
    sku: 'A3959',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    batteryMax: 10,
    names: ['P30i', 'A3959', 'soundcore P30i'],
  },
  {
    id: 'p20i',
    name: 'P20i / P25i',
    sku: 'A3948',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['P20i', 'P25i', 'A3948', 'soundcore P20i', 'soundcore P25i'],
  },
  {
    id: 'liberty-4-nc',
    name: 'Liberty 4 NC',
    sku: 'A3947',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Liberty 4 NC', 'A3947', 'soundcore Liberty 4 NC'],
  },
  {
    id: 'liberty-4',
    name: 'Liberty 4',
    sku: 'A3953',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Liberty 4', 'A3953', 'soundcore Liberty 4'],
  },
  {
    id: 'liberty-3-pro',
    name: 'Liberty 3 Pro',
    sku: 'A3952',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: false,
    scenes: false,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Liberty 3 Pro', 'A3952', 'soundcore Liberty 3 Pro'],
  },
  {
    id: 'space-one',
    name: 'Space One',
    sku: 'A3035',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: true,
    scenes: true,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Space One', 'A3035', 'soundcore Space One'],
  },
  {
    id: 'q45',
    name: 'Space Q45',
    sku: 'A3040',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: true,
    dual: true,
    batteryMax: 5,
    names: ['Q45', 'Space Q45', 'A3040', 'soundcore Space Q45'],
  },
  {
    id: 'q35',
    name: 'Life Q35',
    sku: 'A3029',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: true,
    dual: false,
    batteryMax: 5,
    names: ['Q35', 'Life Q35', 'A3029', 'soundcore Life Q35'],
  },
  {
    id: 'q30',
    name: 'Life Q30',
    sku: 'A3028',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Q30', 'Life Q30', 'A3028', 'Soundcore Life Q30'],
  },
  {
    id: 'life-tune',
    name: 'Life Tune',
    sku: 'A3027',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Life Tune', 'A3027', 'soundcore Life Tune'],
  },
  {
    id: 'sport-x10',
    name: 'Sport X10',
    sku: 'A3961',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Sport X10', 'A3961', 'soundcore Sport X10'],
  },
  {
    id: 'sleep-a10',
    name: 'Sleep A10',
    sku: 'A6610',
    kind: 'earbuds',
    family: 'tws',
    gaming: false,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    batteryMax: 5,
    names: ['Sleep A10', 'A6610', 'soundcore Sleep A10'],
  },
];

export function matchDevice(name: string | undefined | null): DeviceProfile {
  if (!name) return DEVICES[0];
  const n = name.toLowerCase();
  const hit = DEVICES.find((d) =>
    d.names.some((alias) => n.includes(alias.toLowerCase())) || n.includes(d.sku.toLowerCase()),
  );
  return hit ?? DEVICES[0];
}
