import type { DeviceProfile } from '../types';

export const DEVICES: DeviceProfile[] = [
  {
    id: 'r50i-nc',
    name: 'R50i NC',
    sku: 'A3949',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    names: ['R50i', 'A3949', 'soundcore R50i'],
  },
  {
    id: 'p30i',
    name: 'P30i',
    sku: 'A3959',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: false,
    dual: true,
    names: ['P30i', 'A3959'],
  },
  {
    id: 'p20i',
    name: 'P20i / P25i',
    sku: 'A3948',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: false,
    scenes: false,
    ldac: false,
    dual: false,
    names: ['P20i', 'P25i', 'A3948'],
  },
  {
    id: 'liberty-4-nc',
    name: 'Liberty 4 NC',
    sku: 'A3947',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: true,
    scenes: false,
    ldac: true,
    dual: true,
    names: ['Liberty 4 NC', 'A3947'],
  },
  {
    id: 'liberty-3-pro',
    name: 'Liberty 3 Pro',
    sku: 'A3952',
    kind: 'earbuds',
    family: 'tws',
    gaming: true,
    ancLevels: false,
    scenes: false,
    ldac: true,
    dual: true,
    names: ['Liberty 3 Pro', 'A3952'],
  },
  {
    id: 'q30',
    name: 'Life Q30',
    sku: 'A3028',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    names: ['Q30', 'Life Q30', 'A3028', 'Soundcore Life Q30'],
  },
  {
    id: 'q35',
    name: 'Life Q35',
    sku: 'A3029',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: true,
    dual: false,
    names: ['Q35', 'Life Q35', 'A3029'],
  },
  {
    id: 'q45',
    name: 'Space Q45',
    sku: 'A3040',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: true,
    dual: true,
    names: ['Q45', 'Space Q45', 'A3040'],
  },
  {
    id: 'life-tune',
    name: 'Life Tune',
    sku: 'A3027',
    kind: 'overear',
    family: 'classic',
    gaming: false,
    ancLevels: false,
    scenes: true,
    ldac: false,
    dual: false,
    names: ['Life Tune', 'A3027'],
  },
];

export function matchDevice(name: string | undefined | null): DeviceProfile {
  if (!name) return DEVICES[0];
  const n = name.toLowerCase();
  const hit = DEVICES.find((d) =>
    d.names.some((alias) => n.includes(alias.toLowerCase())) || n.includes(d.sku.toLowerCase()),
  );
  return hit ?? DEVICES[0];
}
